api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag)
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

from projects import views

from projects.views import submission_list
urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('python-terminal/', views.python_terminal, name='python-terminal'),
    #path('python-terminal/', views.python_terminal, name='python-terminal'),
    path('run_code/', views.run_code, name='run_code'),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
    path('submissions/', submission_list, name='submissions'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"

projects/urls.py
from django.urls import path
from . import views
from .views import submission_list
urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),
    path('code/', views.code_list, name='code-list'),
    path('create-project/', views.createProject, name="create-project"),
    path('code/<int:pk>/', views.single_code, name='single-code'),
    path('update-project/<str:pk>/', views.updateProject, name="update-project"),

    path('delete-project/<str:pk>/', views.deleteProject, name="delete-project"),
    path('submissions/', submission_list, name='submissions'),
    path('terminal/', views.python_terminal, name='python_terminal'),
    path('run_code/', views.run_code, name='run_code'),
    path('create-code/', views.createCode, name='create-code'),
    path('update-code/<int:pk>/', views.updateCode, name='update-code'),
    path('delete-code/<int:pk>/', views.deleteCode, name='delete-code'),
]

projects/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from users.models import Profile
from django.conf import settings
# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    code = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name
    

class CodeSnippet(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='code_snippets')
    title = models.CharField(max_length=100)
    description = models.TextField(default='')
    file = models.FileField(upload_to='code_snippets/', null=True, blank=True)  # Assuming you're using a FileField
    code = models.TextField() 

class Submission(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_ratio = models.IntegerField(default=0)
    vote_total = models.IntegerField(default=0)
    tags = models.ManyToManyField('Tag')

    def __str__(self):
        return self.title

projects/forms.py
from django.db.models.base import Model
from django.forms import ModelForm, widgets
from django import forms
from .models import Project, Review
from .models import CodeSnippet

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'featured_image', 'description',
                  'demo_link', 'source_link','code']
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

        # self.fields['title'].widget.attrs.update(
        #     {'class': 'input'})

        # self.fields['description'].widget.attrs.update(
        #     {'class': 'input'})


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value', 'body']

        labels = {
            'value': 'Place your vote',
            'body': 'Add a comment with your vote'
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})
class CodeForm(forms.ModelForm):
    class Meta:
        model = CodeSnippet
        fields = ('title', 'description', 'code', 'file') 

projects/views.py
from django.core import paginator
import json
import sys
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Project, Tag
from django.http import JsonResponse
from .forms import ProjectForm, ReviewForm,CodeForm
from .utils import searchProjects, paginateProjects
from subprocess import Popen, PIPE, STDOUT,TimeoutExpired
from .models import CodeSnippet
from django.views.decorators.csrf import csrf_exempt
from .models import Submission
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
def projects(request):
    projects, search_query = searchProjects(request)
    custom_range, projects = paginateProjects(request, projects, 6)

    context = {'projects': projects,
               'search_query': search_query, 'custom_range': custom_range}
    return render(request, 'projects/projects.html', context)

def submission_list(request):
    search_query = request.GET.get('search_query', '')
    if search_query:
        submissions = Submission.objects.filter(title__icontains=search_query)
    else:
        submissions = Submission.objects.all()
    context = {
        'submissions': submissions,
        'search_query': search_query
    }
    return render(request, 'submissions.html', context)
def submission_list(request):
    search_query = request.GET.get('search_query', '')
    submission_list = Submission.objects.filter(title__icontains=search_query) if search_query else Submission.objects.all()
    paginator = Paginator(submission_list, 10) # Show 10 submissions per page.
    page_number = request.GET.get('page')
    submissions = paginator.get_page(page_number)
    context = {
        'submissions': submissions,
        'search_query': search_query
    }
    return render(request, 'projects/submissions.html', context)
def python_terminal(request):
    return render(request, 'terminal.html')

def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.project = projectObj
        review.owner = request.user.profile
        review.save()

        projectObj.getVoteCount

        messages.success(request, 'Your review was successfully submitted!')
        return redirect('project', pk=projectObj.id)

    return render(request, 'projects/single-project.html', {'project': projectObj, 'form': form})


# views.py



@csrf_exempt
def run_code(request):
    data = json.loads(request.body)
    code = data['code']
    python_executable_path = '"C:\Program Files\Python\python.exe"'
    # Create a temporary file to hold the code
    with open('temp_code.py', 'w') as file:
        file.write(code)
    
    # Run the Python script in a separate process
    proc = Popen(['python3', 'temp_code.py'], stdout=PIPE, stderr=STDOUT)
    try:
        # Set a timeout for execution
        output, _ = proc.communicate(timeout=30)
    except TimeoutExpired:
        proc.kill()
        output, _ = proc.communicate()
        output += b'\nError: Execution time exceeded limit.'

    # It's good practice to remove the temp file here
    # os.remove('temp_code.py')
    
    return JsonResponse({'output': output.decode()})


@login_required(login_url="login")
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        newtags_raw = request.POST.get('newtags')
        
        # Check if 'newtags' is provided to prevent AttributeError
        newtags = newtags_raw.replace(',', " ").split() if newtags_raw else []

        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()

            # Create new tags if they do not exist and add them to the project
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag.strip())
                project.tags.add(tag)
            messages.success(request, 'Project created successfully!')
            return redirect('account')

    context = {'form': form}
    return render(request, "projects/project_form.html", context)



@login_required(login_url="login")
def updateProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()

            # Get the tags from the form. If 'newtags' is None, default to an empty string.
            newtags_str = request.POST.get('newtags', '')
            newtags_list = [tag.strip() for tag in newtags_str.replace(',', ' ').split()]

            # Clear existing tags and add new ones
            project.tags.clear()
            for tag_name in newtags_list:
                if tag_name:  # Ensure that tag_name is not an empty string
                    tag, created = Tag.objects.get_or_create(name=tag_name)
                    project.tags.add(tag)

            return redirect('account')

    context = {'form': form, 'project': project}
    return render(request, "projects/project_form.html", context)



@login_required(login_url="login")
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects')
    context = {'object': project}
    return render(request, 'delete_template.html', context)


@login_required(login_url="login")
def createCode(request):
    profile = request.user.profile
    form = CodeForm()
    
    if request.method == 'POST':
        form = CodeForm(request.POST, request.FILES)
        if form.is_valid():
            code_snippet = form.save(commit=False)
            code_snippet.user = request.user 
            code_snippet.save()
            messages.success(request, 'Code snippet added successfully!')
            return redirect('account')

    context = {'form': form}
    return render(request, "projects/codeForm.html", context)


@login_required(login_url="login")
def updateCode(request, pk):
    profile = request.user.profile
    code_snippet = profile.code_set.get(id=pk)
    
    form = CodeForm(instance=code_snippet)
    
    if request.method == 'POST':
        form = CodeForm(request.POST, request.FILES, instance=code_snippet)
        if form.is_valid():
            form.save()
            messages.success(request, 'Code snippet updated successfully!')
            return redirect('account')

    context = {'form': form, 'code_snippet': code_snippet}
    return render(request, "projects/codeForm.html", context)


@login_required(login_url="login")
def deleteCode(request, pk):
    profile = request.user.profile
    code_snippet = profile.code_set.get(id=pk)
    if request.method == 'POST':
        code_snippet.delete()
        messages.success(request, 'Code snippet deleted successfully!')
        return redirect('account')

    context = {'object': code_snippet}
    return render(request, 'delete_template.html', context)

@login_required
def get_user_code(request):
    # Get the user's latest code snippet
    code_snippet = CodeSnippet.objects.filter(user=request.user).last()
    
    if code_snippet:
        return JsonResponse({'code': code_snippet.code}, status=200)
    else:
        return JsonResponse({'error': 'No code found.'}, status=404)
    
def code_list(request):
    code_snippets = CodeSnippet.objects.all()  # Or any other logic to get the code snippets
    context = {'code_snippets': code_snippets}
    return render(request, 'projects/code_list.html', context)

def single_code(request, pk):
    code_snippet = get_object_or_404(CodeSnippet, pk=pk)
    context = {
        'code_snippet': code_snippet
    }
    return render(request, 'projects/single_code.html', context)

projects/templates/projects/codeForm.html
{% extends 'main.html' %}
{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i> Return to Account</a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Loop through the fields in the form -->
                {% for field in form %}
                <div class="form__field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
                {% endfor %}

                <!-- Additional field specific to code submission -->
                <div class="form__field">
                    <label for="id_code_file">Upload your code file</label>
                    <input type="file" name="code_file" id="id_code_file" class="input">
                    <small class="form-text text-muted">Attach your code file here (optional).</small>
                </div>

                <!-- Textarea for submitting code directly -->
                <div class="form__field">
                    <label for="id_code">Code Snippet</label>
                    <textarea name="code" id="id_code" class="input" rows="10">{{ form.instance.code }}</textarea>
                    <small class="form-text text-muted">Paste your source code here if not uploading a file.</small>
                </div>

                <input class="btn btn--sub btn--lg my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

projects/templates/projects/code_list.html
{% extends 'main.html' %}
{% block content %}

<!-- Main Section -->
<main class="codes">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Search for <span>Code</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'code-list' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search By Code Title</label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by Code Title" value="{{ search_query }}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: CodeList -->
    <section class="codesList">
        <div class="container">
            <div class="grid grid--three">
                {% for code_snippet in code_snippets %}
                <div class="column">
                    <div class="card code">
                        <a href="{% url 'single-code' code_snippet.id %}"> <!-- Make sure 'single-code' is the name of your detail view url -->
                            <img class="code__thumbnail" src="{{ code_snippet.imageURL }}" alt="{{ code_snippet.title }}">
                            <div class="card__body">
                                <h3 class="code__title">{{ code_snippet.title }}</h3>
                                <p class="code__description">{{ code_snippet.description|truncatechars:100 }}</p>
                                <!-- Add a link or button if you want to make a separate clickable area -->
                            </div>
                        </a>
                    </div>
                </div>
                {% empty %}
                <p>No code submissions available.</p>
                {% endfor %}
            </div>
        </div>
    </section>

    {% include 'pagination.html' with queryset=code_snippets custom_range=custom_range %}
</main>

{% endblock %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}
{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
                {% endfor %}

                <!-- Field for submitting dataset -->
                <div class="form__field">
                    <label for="id_dataset">Submit your dataset</label>
                    <input type="file" name="dataset" id="id_dataset" class="input">
                    <small class="form-text text-muted">Attach your dataset file here.</small>
                </div>

                <!-- Field for submitting code -->
                <div class="form__field">
                    <label for="id_code">Submit your code</label>
                    <textarea name="code" class="input">{{ form.instance.code }}</textarea>
                    <small class="form-text text-muted">Paste your source code.</small>
                </div>

                <input class="btn btn--sub btn--lg my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}
{% block content %}


<!-- Main Section -->
<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Search for <span>Dataset</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'projects' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search By Dataset </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by Project Title" value="{{search_query}}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">

                {% for project in projects %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'project' project.id %}" class="project">
                            <img class="project__thumbnail" src="{{project.imageURL}}" alt="project thumbnail" />
                            <div class="card__body">
                                <h3 class="project__title">{{project.title}}</h3>
                                <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By
                                        {{project.owner.name}}</a>
                                </p>
                                <p class="project--rating">
                                    <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Positive
                                    Feedback ({{project.vote_total}}) Vote{{project.vote_total|pluralize:"s"}}
                                </p>
                                <div class="project__tags">
                                    {% for tag in project.tags.all %}
                                    <span class="tag tag--pill tag--main">
                                        <small>{{tag}}</small>
                                    </span>
                                    {% endfor %}

                                </div>
                            </div>
                           

                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    {% include 'pagination.html' with queryset=projects custom_range=custom_range %}

</main>




{% endblock %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <!-- Redesigned Button -->
                <button class="button--styled" onclick="window.location.href='/python-terminal';">Open Python Terminal</button>
                <h3 class="singleProject__subtitle">Tools & Stacks</h3>

                <div class="singleProject__toolStack">
                    {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{ tag }}</small>
                    </span>
                    {% endfor %}
                </div>

                {% if project.source_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i class="im im-external-link"></i>Source Code</a>
                {% endif %}

                {% if project.demo_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i class="im im-external-link"></i>Live Demo</a>
                {% endif %}
            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
                <a href="{% url 'user-profile' project.owner.id %}" class="singleProject__developer">{{ project.owner.name }}</a>
                <h2 class="singleProject__title">{{ project.title }}</h2>

                <h3 class="singleProject__subtitle">About the Dataset</h3>
                <div class="singleProject__info">
                    {{ project.description }}
                </div>
                <div class="user-code">
                    <h2>User Code</h2>
                    
<pre>{{ project.code }}</pre>
                </div>
                
                
            
                
                <!-- Comments and Reviews Section -->
                <div class="comments">
                    <h3 class="singleProject__subtitle">Feedback</h3>
                    <!-- Feedback and reviews content -->
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

<!-- Additional CSS for Button and Cards -->
<style>
.button--styled {
    background-color: #007bff; /* Primary Blue */
    color: white;
    border: none;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    transition-duration: 0.4s;
    cursor: pointer;
    border-radius: 5px;
}

.button--styled:hover {
    background-color: #0056b3; /* Darker blue */
    color: white;
}

.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 40%;
    border-radius: 5px;
    display: inline-block; /* To display cards side by side */
    margin: 10px;
}

.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.card__image {
    border-radius: 5px 5px 0 0;
    width: 100%;
}

.card__body {
    padding: 2px 16px;
}

.card__title {
    font-weight: bold;
}

.card__description {
    color: grey;
}


.tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    /* Style the buttons inside the tab */
    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    /* Change background color of buttons on hover */
    .tab button:hover {
        background-color: #ddd;
    }

    /* Create an active/current tablink class */
    .tab button.active {
        background-color: #ccc;
    }

    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

<script>
    function openTab(evt, tabName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
 </script>










// Optionally, you can use this to click on the first tab by default when the page loads
document.addEventListener('DOMContentLoaded', (event) => {
    // Click the first tab by default if it exists
    var firstTab = document.querySelector(".tablinks");
    if (firstTab) {
        firstTab.click();
    }
});

</script>